In [1]:
#Question1

In [5]:
import numpy as np
a=np.array ([[5,6,7],[8,9,10]])
a

array([[ 5,  6,  7],
       [ 8,  9, 10]])

In [6]:
# array to list 
a.tolist()

[[5, 6, 7], [8, 9, 10]]

In [7]:
#Question2

In [23]:
b=np.array([[5,6,7],[8,9,10],[1,2,3]])
b

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [ 1,  2,  3]])

In [26]:
b.shape

(3, 3)

In [25]:
t=np.trace(b)
print(t)

17


In [28]:
s=b.diagonal()
print(s)

[5 9 3]


In [29]:
B=b(0,0)+b(1,1)+b(2,2)

TypeError: 'numpy.ndarray' object is not callable

In [30]:
#Question3

In [32]:
c=np.array([[1,2],[3,5]])
X=2
c

array([[1, 2],
       [3, 5]])

In [33]:
print("value bigger than X",c[c>X])

value bigger than X [3 5]


In [34]:
#Question4

In [36]:
A=np.array([[6,7,8],[2,3,4]])
B=np.array([[7,8,9],[1,2,3]])
A,B

(array([[6, 7, 8],
        [2, 3, 4]]),
 array([[7, 8, 9],
        [1, 2, 3]]))

In [38]:
C=A+B
C

array([[13, 15, 17],
       [ 3,  5,  7]])

In [39]:
#Question5

In [43]:
A.mean()

5.0